# Install package dart_code_metrics as a global package and run it as a console command if you want to use this file.
# I basically don't use it as a dev dependency because it's slow as hell sometimes.

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - /**.g.dart

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-setstate
    - avoid-non-null-assertion
    - double-literal-format
    - avoid-unused-parameters:
        severity: info
