analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - /**.g.dart

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-setstate
    - avoid-non-null-assertion
    - double-literal-format
    - avoid-unused-parameters:
        severity: info
